/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.nio.charset.Charset;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import static java.nio.file.Files.readAllLines;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Scanner;

/**
 *
 * @author nilton.brito
 */
public class TelaConfiguracao extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaConfiguracao
     */
    public TelaConfiguracao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        painelDataCadastro = new javax.swing.JPanel();
        lblDataCad = new javax.swing.JLabel();
        painelId = new javax.swing.JPanel();
        txtId = new javax.swing.JTextField();
        painelDadosCadastrais = new javax.swing.JPanel();
        lblNomeEmpresa = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblCnpj = new javax.swing.JLabel();
        txtNomeEmpresa = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtCnpj = new javax.swing.JFormattedTextField();
        lblResponsavel = new javax.swing.JLabel();
        txtResponsavel = new javax.swing.JTextField();
        lblTipo = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        lblCelular = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JFormattedTextField();
        txtCelular = new javax.swing.JFormattedTextField();
        txtTipo = new javax.swing.JTextField();
        painelDadosEndereco = new javax.swing.JPanel();
        lblBairro = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        lblCidade = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox<>();
        lblCep = new javax.swing.JLabel();
        txtCep = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        lblEndereco = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        lblComplemento = new javax.swing.JLabel();
        txtComplemento = new javax.swing.JTextField();
        lblComplemento2 = new javax.swing.JLabel();
        txtComplemento2 = new javax.swing.JTextField();
        lblNumero = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        lblStatusCep = new javax.swing.JLabel();
        painelFuncoes = new javax.swing.JPanel();
        btnAdicionar = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        painelPesquisar = new javax.swing.JPanel();
        txtPesquisar = new javax.swing.JTextField();
        lblPesquisar = new javax.swing.JLabel();
        lblCliCamposObrigatorios = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblNovoproduto = new javax.swing.JLabel();
        ckbCliente = new javax.swing.JCheckBox();
        txtNovoPerfil = new javax.swing.JTextField();
        cmbConfigPerfil = new javax.swing.JComboBox<>();
        btnExcluirPerfil = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        ckbFuncionario = new javax.swing.JCheckBox();
        ckbOS = new javax.swing.JCheckBox();
        ckbEmpresa = new javax.swing.JCheckBox();
        ckbEstoque = new javax.swing.JCheckBox();
        ckbRelCliente = new javax.swing.JCheckBox();
        ckbRelFuncionario = new javax.swing.JCheckBox();
        ckbRelServico = new javax.swing.JCheckBox();
        ckbRelFinanceiro = new javax.swing.JCheckBox();
        ckbRelConfigSistema = new javax.swing.JCheckBox();
        btnAdd = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Configurações do Sistema");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ico.png"))); // NOI18N
        setPreferredSize(new java.awt.Dimension(1080, 650));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(1070, 618));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        painelDataCadastro.setBorder(javax.swing.BorderFactory.createTitledBorder("Data do Cadastro:"));
        painelDataCadastro.setForeground(new java.awt.Color(0, 0, 0));
        painelDataCadastro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDataCad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDataCad.setForeground(new java.awt.Color(0, 0, 0));
        lblDataCad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        painelDataCadastro.add(lblDataCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 180, 30));

        jPanel1.add(painelDataCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 200, 60));

        painelId.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro ID"));
        painelId.setForeground(new java.awt.Color(0, 0, 0));
        painelId.setPreferredSize(new java.awt.Dimension(120, 70));
        painelId.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtId.setEditable(false);
        txtId.setForeground(new java.awt.Color(0, 0, 0));
        txtId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        painelId.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 80, 30));

        jPanel1.add(painelId, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 60));

        painelDadosCadastrais.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Cadastrais"));
        painelDadosCadastrais.setForeground(new java.awt.Color(0, 0, 0));
        painelDadosCadastrais.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNomeEmpresa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNomeEmpresa.setForeground(new java.awt.Color(0, 0, 0));
        lblNomeEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNomeEmpresa.setText("*Nome Empresa:");
        painelDadosCadastrais.add(lblNomeEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, 30));

        lblEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(0, 0, 0));
        lblEmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEmail.setText("*E-mail:");
        painelDadosCadastrais.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 30));

        lblCnpj.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCnpj.setForeground(new java.awt.Color(0, 0, 0));
        lblCnpj.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCnpj.setText("*CNPJ:");
        painelDadosCadastrais.add(lblCnpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 30));

        txtNomeEmpresa.setForeground(new java.awt.Color(0, 0, 0));
        painelDadosCadastrais.add(txtNomeEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 360, 30));

        txtEmail.setForeground(new java.awt.Color(0, 0, 0));
        painelDadosCadastrais.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 250, 30));

        txtCnpj.setForeground(new java.awt.Color(0, 0, 0));
        try {
            txtCnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        painelDadosCadastrais.add(txtCnpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 150, 30));

        lblResponsavel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblResponsavel.setForeground(new java.awt.Color(0, 0, 0));
        lblResponsavel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblResponsavel.setText("Responsavel:");
        painelDadosCadastrais.add(lblResponsavel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, -1, 30));
        painelDadosCadastrais.add(txtResponsavel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 270, 30));

        lblTipo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTipo.setForeground(new java.awt.Color(0, 0, 0));
        lblTipo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTipo.setText("Tipo:");
        painelDadosCadastrais.add(lblTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 30));

        lblTelefone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTelefone.setForeground(new java.awt.Color(0, 0, 0));
        lblTelefone.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTelefone.setText("Telefone:");
        painelDadosCadastrais.add(lblTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, -1, 30));

        lblCelular.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCelular.setForeground(new java.awt.Color(0, 0, 0));
        lblCelular.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCelular.setText("*Celular:");
        painelDadosCadastrais.add(lblCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, 30));

        txtTelefone.setForeground(new java.awt.Color(0, 0, 0));
        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        painelDadosCadastrais.add(txtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 150, 30));

        txtCelular.setForeground(new java.awt.Color(0, 0, 0));
        try {
            txtCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        painelDadosCadastrais.add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 150, 30));
        painelDadosCadastrais.add(txtTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 150, 30));

        jPanel1.add(painelDadosCadastrais, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 730, 160));

        painelDadosEndereco.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados de Endereço"));
        painelDadosEndereco.setForeground(new java.awt.Color(0, 0, 0));
        painelDadosEndereco.setPreferredSize(new java.awt.Dimension(680, 120));
        painelDadosEndereco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBairro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblBairro.setForeground(new java.awt.Color(0, 0, 0));
        lblBairro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBairro.setText("Bairro:");
        painelDadosEndereco.add(lblBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 30));

        txtBairro.setForeground(new java.awt.Color(0, 0, 0));
        painelDadosEndereco.add(txtBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 200, 30));

        lblCidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCidade.setForeground(new java.awt.Color(0, 0, 0));
        lblCidade.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCidade.setText("Cidade:");
        painelDadosEndereco.add(lblCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, 30));

        lblEstado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEstado.setForeground(new java.awt.Color(0, 0, 0));
        lblEstado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEstado.setText("Estado:");
        painelDadosEndereco.add(lblEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, -1, 30));

        cmbEstado.setForeground(new java.awt.Color(0, 0, 0));
        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        cmbEstado.setMinimumSize(new java.awt.Dimension(80, 22));
        cmbEstado.setPreferredSize(new java.awt.Dimension(80, 22));
        painelDadosEndereco.add(cmbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, 90, 30));

        lblCep.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCep.setForeground(new java.awt.Color(0, 0, 0));
        lblCep.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCep.setText("*CEP:");
        painelDadosEndereco.add(lblCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 30));

        txtCep.setForeground(new java.awt.Color(0, 0, 0));
        txtCep.setMinimumSize(new java.awt.Dimension(60, 22));
        txtCep.setPreferredSize(new java.awt.Dimension(60, 22));
        txtCep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCepKeyReleased(evt);
            }
        });
        painelDadosEndereco.add(txtCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 150, 30));

        txtCidade.setForeground(new java.awt.Color(0, 0, 0));
        painelDadosEndereco.add(txtCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 230, 30));

        lblEndereco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEndereco.setForeground(new java.awt.Color(0, 0, 0));
        lblEndereco.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEndereco.setText("Endereço:");
        painelDadosEndereco.add(lblEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, 30));

        txtEndereco.setForeground(new java.awt.Color(0, 0, 0));
        painelDadosEndereco.add(txtEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 280, 30));

        lblComplemento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblComplemento.setForeground(new java.awt.Color(0, 0, 0));
        lblComplemento.setText("Complemento:");
        painelDadosEndereco.add(lblComplemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 30));

        txtComplemento.setForeground(new java.awt.Color(0, 0, 0));
        painelDadosEndereco.add(txtComplemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 230, 30));

        lblComplemento2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblComplemento2.setForeground(new java.awt.Color(0, 0, 0));
        lblComplemento2.setText("Complemento:");
        painelDadosEndereco.add(lblComplemento2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, -1, 30));

        txtComplemento2.setForeground(new java.awt.Color(0, 0, 0));
        painelDadosEndereco.add(txtComplemento2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 230, 30));

        lblNumero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNumero.setForeground(new java.awt.Color(0, 0, 0));
        lblNumero.setText("Nº");
        painelDadosEndereco.add(lblNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 30, -1, 30));

        txtNumero.setForeground(new java.awt.Color(0, 0, 0));
        painelDadosEndereco.add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, 60, 30));
        painelDadosEndereco.add(lblStatusCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 30, 30));

        jPanel1.add(painelDadosEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 730, 160));

        painelFuncoes.setBorder(javax.swing.BorderFactory.createTitledBorder("Funções"));
        painelFuncoes.setForeground(new java.awt.Color(0, 0, 0));
        painelFuncoes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add - large.png"))); // NOI18N
        btnAdicionar.setToolTipText("Adicionar cliente");
        btnAdicionar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        painelFuncoes.add(btnAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        btnDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete - large.png"))); // NOI18N
        btnDeletar.setToolTipText("Deletar cliente");
        btnDeletar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeletar.setEnabled(false);
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });
        painelFuncoes.add(btnDeletar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/edit - large.png"))); // NOI18N
        btnEditar.setToolTipText("Alterar dados do cliente");
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditar.setEnabled(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        painelFuncoes.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/limpar - large.png"))); // NOI18N
        btnLimpar.setToolTipText("Limpar formulário");
        btnLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        painelFuncoes.add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        jPanel1.add(painelFuncoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 30, 240, 240));

        painelPesquisar.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisar"));
        painelPesquisar.setForeground(new java.awt.Color(0, 0, 0));
        painelPesquisar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPesquisar.setForeground(new java.awt.Color(0, 0, 0));
        txtPesquisar.setToolTipText("Pesquisa dinâmica do usuário");
        txtPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarKeyReleased(evt);
            }
        });
        painelPesquisar.add(txtPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 230, 30));

        lblPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search_icon.png"))); // NOI18N
        painelPesquisar.add(lblPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 30, -1));

        jPanel1.add(painelPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 330, 300, 60));

        lblCliCamposObrigatorios.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCliCamposObrigatorios.setForeground(new java.awt.Color(204, 0, 0));
        lblCliCamposObrigatorios.setText("*Campos Obrigatórios");
        jPanel1.add(lblCliCamposObrigatorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 310, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ajustes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel2.setLayout(null);

        lblNovoproduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNovoproduto.setText("Perfil:");
        jPanel2.add(lblNovoproduto);
        lblNovoproduto.setBounds(20, 20, 33, 30);

        ckbCliente.setText("Cadastro de Clientes");
        jPanel2.add(ckbCliente);
        ckbCliente.setBounds(20, 90, 170, 20);

        txtNovoPerfil.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtNovoPerfil.setForeground(new java.awt.Color(0, 51, 204));
        jPanel2.add(txtNovoPerfil);
        txtNovoPerfil.setBounds(60, 20, 150, 30);

        cmbConfigPerfil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Administrador" }));
        cmbConfigPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbConfigPerfilActionPerformed(evt);
            }
        });
        jPanel2.add(cmbConfigPerfil);
        cmbConfigPerfil.setBounds(60, 60, 150, 30);

        btnExcluirPerfil.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExcluirPerfil.setText("Excluir");
        btnExcluirPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirPerfilActionPerformed(evt);
            }
        });
        jPanel2.add(btnExcluirPerfil);
        btnExcluirPerfil.setBounds(220, 60, 100, 30);

        btnSalvar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jPanel2.add(btnSalvar);
        btnSalvar.setBounds(370, 160, 72, 30);

        ckbFuncionario.setText("Cadastro de Funcionários");
        jPanel2.add(ckbFuncionario);
        ckbFuncionario.setBounds(20, 110, 170, 20);

        ckbOS.setText("Cadastro de OS");
        jPanel2.add(ckbOS);
        ckbOS.setBounds(20, 130, 170, 20);

        ckbEmpresa.setText("Cadastro de Empresa");
        jPanel2.add(ckbEmpresa);
        ckbEmpresa.setBounds(20, 150, 170, 20);

        ckbEstoque.setText("Cadastro de Estoque");
        jPanel2.add(ckbEstoque);
        ckbEstoque.setBounds(20, 170, 170, 20);

        ckbRelCliente.setText("Relatório de Clientes");
        jPanel2.add(ckbRelCliente);
        ckbRelCliente.setBounds(190, 90, 170, 20);

        ckbRelFuncionario.setText("Relatório de Funcionários");
        jPanel2.add(ckbRelFuncionario);
        ckbRelFuncionario.setBounds(190, 110, 170, 20);

        ckbRelServico.setText("Relatório de Serviços");
        jPanel2.add(ckbRelServico);
        ckbRelServico.setBounds(190, 130, 170, 20);

        ckbRelFinanceiro.setText("Relatório Financeiro");
        jPanel2.add(ckbRelFinanceiro);
        ckbRelFinanceiro.setBounds(190, 150, 170, 20);

        ckbRelConfigSistema.setText("Configurações do Sistema");
        jPanel2.add(ckbRelConfigSistema);
        ckbRelConfigSistema.setBounds(190, 170, 170, 20);

        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdd.setText("Adicionar");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel2.add(btnAdd);
        btnAdd.setBounds(220, 20, 100, 30);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 460, 210));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 618));

        setBounds(0, 0, 1080, 650);
    }// </editor-fold>//GEN-END:initComponents

    public void lerConfig() throws IOException {
        //List<String> linhas = readAllLines(Paths.get("C:\\Users\\nilton.brito\\Documents\\NetBeansProjects\\Bandampla\\src\\view\\settings.txt"), Charset.defaultCharset());
        // String texto = Files.readString(Paths.get("C:\\Users\\nilton.brito\\Documents\\NetBeansProjects\\Bandampla\\src\\view\\settings.txt"), StandardCharsets.UTF_8);
        Scanner in = new Scanner(new FileReader("C:\\Users\\nilton.brito\\Documents\\NetBeansProjects\\Bandampla\\src\\view\\settings.txt"));
        while (in.hasNextLine()) {
            String line = in.nextLine();
            System.out.println(line);
            cmbConfigPerfil.addItem(line);
        }
    }

    public String salvar() {

        LocalDateTime datahora = LocalDateTime.now();
        DateTimeFormatter formatada = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
        String dataAgora = (datahora.format(formatada));

        if (cmbConfigPerfil.getSelectedItem().toString().isEmpty()) {
            return ("Escolha um Perfil!");
        } else {
            try {
                FileWriter criaraqruivo = new FileWriter("C:\\Users\\nilton.brito\\Documents\\NetBeansProjects\\Bandampla\\src\\view\\settings.txt", true);
                PrintWriter gravararquivo = new PrintWriter(criaraqruivo);
                // Salva os dados
                gravararquivo.println("Perfil: " + cmbConfigPerfil.getSelectedItem().toString());
                gravararquivo.println("Atualizado em: " + ckbCliente);
                gravararquivo.println("Atualizado em: " + ckbEmpresa);
                gravararquivo.println("Atualizado em: " + ckbEstoque);
                gravararquivo.println("Atualizado em: " + ckbFuncionario);
                gravararquivo.println("Atualizado em: " + ckbOS);
                gravararquivo.println("Atualizado em: " + ckbRelCliente);
                gravararquivo.println("Atualizado em: " + ckbRelConfigSistema);
                gravararquivo.println("Atualizado em: " + ckbRelFinanceiro);
                gravararquivo.println("Atualizado em: " + ckbRelFuncionario);
                gravararquivo.println("Atualizado em: " + ckbRelServico);
                gravararquivo.println("Atualizado em: " + dataAgora);
                
                
                //Enviar os dados automativo para o txt
                gravararquivo.flush();
            } catch (IOException e) {

            }
            return ("Cadastrado realizado com Sucesso!");
        }
    }
    private void txtCepKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCepKeyReleased

    }//GEN-LAST:event_txtCepKeyReleased

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed

    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed

    }//GEN-LAST:event_btnDeletarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
;
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed

    }//GEN-LAST:event_btnLimparActionPerformed

    private void txtPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarKeyReleased

    }//GEN-LAST:event_txtPesquisarKeyReleased

    private void cmbConfigPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbConfigPerfilActionPerformed
        // TODO add your handling code here:
        String perfilSelecionado = cmbConfigPerfil.getSelectedItem().toString();
        cmbConfigPerfil.setSelectedItem(perfilSelecionado);
        cmbConfigPerfil.setSelectedItem("");
    }//GEN-LAST:event_cmbConfigPerfilActionPerformed

    private void btnExcluirPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirPerfilActionPerformed
        // TODO add your handling code here:
        String perfilSelecionado = cmbConfigPerfil.getSelectedItem().toString();
        cmbConfigPerfil.removeItem(perfilSelecionado);
    }//GEN-LAST:event_btnExcluirPerfilActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        salvar();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String novoPerfil = txtNovoPerfil.getText();
        cmbConfigPerfil.addItem(novoPerfil);
        txtNovoPerfil.setText("");
    }//GEN-LAST:event_btnAddActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        try {
            // TODO add your handling code here:
            lerConfig();
        } catch (IOException ex) {
        }
    }//GEN-LAST:event_formInternalFrameOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    public static javax.swing.JButton btnAdicionar;
    public static javax.swing.JButton btnDeletar;
    public static javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluirPerfil;
    public static javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JCheckBox ckbCliente;
    private javax.swing.JCheckBox ckbEmpresa;
    private javax.swing.JCheckBox ckbEstoque;
    private javax.swing.JCheckBox ckbFuncionario;
    private javax.swing.JCheckBox ckbOS;
    private javax.swing.JCheckBox ckbRelCliente;
    private javax.swing.JCheckBox ckbRelConfigSistema;
    private javax.swing.JCheckBox ckbRelFinanceiro;
    private javax.swing.JCheckBox ckbRelFuncionario;
    private javax.swing.JCheckBox ckbRelServico;
    private javax.swing.JComboBox<String> cmbConfigPerfil;
    public static javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblCep;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblCliCamposObrigatorios;
    private javax.swing.JLabel lblCnpj;
    private javax.swing.JLabel lblComplemento;
    private javax.swing.JLabel lblComplemento2;
    public static javax.swing.JLabel lblDataCad;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblNomeEmpresa;
    private javax.swing.JLabel lblNovoproduto;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblPesquisar;
    private javax.swing.JLabel lblResponsavel;
    public static javax.swing.JLabel lblStatusCep;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JPanel painelDadosCadastrais;
    private javax.swing.JPanel painelDadosEndereco;
    private javax.swing.JPanel painelDataCadastro;
    private javax.swing.JPanel painelFuncoes;
    private javax.swing.JPanel painelId;
    private javax.swing.JPanel painelPesquisar;
    public static javax.swing.JTextField txtBairro;
    public static javax.swing.JFormattedTextField txtCelular;
    public static javax.swing.JTextField txtCep;
    public static javax.swing.JTextField txtCidade;
    public static javax.swing.JFormattedTextField txtCnpj;
    public static javax.swing.JTextField txtComplemento;
    public static javax.swing.JTextField txtComplemento2;
    public static javax.swing.JTextField txtEmail;
    public static javax.swing.JTextField txtEndereco;
    public static javax.swing.JTextField txtId;
    public static javax.swing.JTextField txtNomeEmpresa;
    private javax.swing.JTextField txtNovoPerfil;
    public static javax.swing.JTextField txtNumero;
    public static javax.swing.JTextField txtPesquisar;
    public static javax.swing.JTextField txtResponsavel;
    public static javax.swing.JFormattedTextField txtTelefone;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
