/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import Atxy2k.CustomTextField.RestrictedTextField;
import business.EmpresaBS;
import java.sql.SQLException;
import model.Empresa;

/**
 *
 * @author nilton.brito
 */
public class TelaCadastroEmpresa extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaCadastroEmpresa
     */
    public TelaCadastroEmpresa() {
        initComponents();
        RestrictedTextField validarCnpj = new RestrictedTextField(txtCnpj);
        validarCnpj.setOnlyNums(true);
        validarCnpj.setLimit(14);
        RestrictedTextField validarInscriçãoEstadual;
        validarInscriçãoEstadual = new RestrictedTextField(txtInscricaoEstadual);
        validarInscriçãoEstadual.setOnlyNums(true);
        validarInscriçãoEstadual.setLimit(12);
        RestrictedTextField validarCep = new RestrictedTextField(txtCep);
        validarCep.setOnlyNums(true);
        validarCep.setLimit(8);
        RestrictedTextField validarNome = new RestrictedTextField(txtNome);
        validarNome.setLimit(50);
        RestrictedTextField validarCapitalSocial = new RestrictedTextField(txtCapitalSocial);
        validarCapitalSocial.setLimit(18);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelId = new javax.swing.JPanel();
        txtId = new javax.swing.JTextField();
        painelDadosCadastrais = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        lblCnpj = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblNomeFantasia = new javax.swing.JLabel();
        txtNomeFantasia = new javax.swing.JTextField();
        txtCnpj = new javax.swing.JTextField();
        lblTipo = new javax.swing.JLabel();
        txtTipo = new javax.swing.JTextField();
        lblSituacaoCadastral = new javax.swing.JLabel();
        txtSituacaoCadastral = new javax.swing.JTextField();
        lblPorte = new javax.swing.JLabel();
        txtPorte = new javax.swing.JTextField();
        lblDataAbertura = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblInscricaoEstadual = new javax.swing.JLabel();
        txtInscricaoEstadual = new javax.swing.JTextField();
        lblDataSituacaoCadastral = new javax.swing.JLabel();
        lblCapitalSocial = new javax.swing.JLabel();
        lblNaturezaJuridica = new javax.swing.JLabel();
        txtNaturezaJuridica = new javax.swing.JTextField();
        txtDataAbertura = new javax.swing.JFormattedTextField();
        txtDataSituacaoCadastral = new javax.swing.JFormattedTextField();
        txtCapitalSocial = new javax.swing.JTextField();
        lblStatusCnpj = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAtividadePrincipal = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAtividadeSecundaria = new javax.swing.JTextArea();
        painelDadosEndereco = new javax.swing.JPanel();
        lblBairro = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        lblCidade = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox<>();
        lblCep = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        lblEndereco = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        lblComplemento = new javax.swing.JLabel();
        txtComplemento = new javax.swing.JTextField();
        lblNumero = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        lblStatusCep = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JFormattedTextField();
        btnCep = new javax.swing.JButton();
        txtCep = new javax.swing.JTextField();
        painelFuncoes = new javax.swing.JPanel();
        btnAdicionar = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        painelDataCadastro = new javax.swing.JPanel();
        txtDataCadastro = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        txtResponsalvel = new javax.swing.JTextField();
        lblResponsavel = new javax.swing.JLabel();
        lblCelular = new javax.swing.JLabel();
        txtCelular = new javax.swing.JFormattedTextField();
        lblCliCamposObrigatorios = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastro da Empresa");
        setPreferredSize(new java.awt.Dimension(1080, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        painelId.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Funções", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        painelId.setPreferredSize(new java.awt.Dimension(120, 70));
        painelId.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtId.setEditable(false);
        txtId.setForeground(new java.awt.Color(0, 0, 0));
        txtId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        painelId.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 70, 30));

        getContentPane().add(painelId, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, 90, 60));

        painelDadosCadastrais.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Funções", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        painelDadosCadastrais.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNome.setForeground(new java.awt.Color(0, 0, 0));
        lblNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNome.setText("*Nome");
        painelDadosCadastrais.add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 30));

        lblCnpj.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCnpj.setForeground(new java.awt.Color(0, 0, 0));
        lblCnpj.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCnpj.setText("*Cnpj");
        painelDadosCadastrais.add(lblCnpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 30));

        txtNome.setForeground(new java.awt.Color(0, 0, 0));
        painelDadosCadastrais.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 400, 30));

        lblNomeFantasia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNomeFantasia.setForeground(new java.awt.Color(0, 0, 0));
        lblNomeFantasia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNomeFantasia.setText("Nome Fantasia");
        painelDadosCadastrais.add(lblNomeFantasia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, 30));

        txtNomeFantasia.setForeground(new java.awt.Color(0, 0, 0));
        painelDadosCadastrais.add(txtNomeFantasia, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 350, 30));

        txtCnpj.setForeground(new java.awt.Color(0, 0, 0));
        txtCnpj.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCnpj.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCnpjKeyReleased(evt);
            }
        });
        painelDadosCadastrais.add(txtCnpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 150, 30));

        lblTipo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTipo.setForeground(new java.awt.Color(0, 0, 0));
        lblTipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTipo.setText("Tipo");
        painelDadosCadastrais.add(lblTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, 30));

        txtTipo.setForeground(new java.awt.Color(0, 0, 0));
        txtTipo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        painelDadosCadastrais.add(txtTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 90, 30));

        lblSituacaoCadastral.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSituacaoCadastral.setForeground(new java.awt.Color(0, 0, 0));
        lblSituacaoCadastral.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSituacaoCadastral.setText("*Situação Cadastral");
        painelDadosCadastrais.add(lblSituacaoCadastral, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, -1, 30));

        txtSituacaoCadastral.setForeground(new java.awt.Color(0, 0, 0));
        txtSituacaoCadastral.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        painelDadosCadastrais.add(txtSituacaoCadastral, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 100, 90, 30));

        lblPorte.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPorte.setForeground(new java.awt.Color(0, 0, 0));
        lblPorte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPorte.setText("Porte");
        painelDadosCadastrais.add(lblPorte, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, -1, 30));

        txtPorte.setForeground(new java.awt.Color(0, 0, 0));
        txtPorte.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        painelDadosCadastrais.add(txtPorte, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 180, 120, 30));

        lblDataAbertura.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDataAbertura.setForeground(new java.awt.Color(0, 0, 0));
        lblDataAbertura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDataAbertura.setText("Data de Abertura");
        painelDadosCadastrais.add(lblDataAbertura, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, -1, 30));

        lblEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(0, 0, 0));
        lblEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmail.setText("*E-mail");
        painelDadosCadastrais.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 30));

        txtEmail.setForeground(new java.awt.Color(0, 0, 0));
        painelDadosCadastrais.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 340, 30));

        lblInscricaoEstadual.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblInscricaoEstadual.setForeground(new java.awt.Color(0, 0, 0));
        lblInscricaoEstadual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInscricaoEstadual.setText("IE");
        painelDadosCadastrais.add(lblInscricaoEstadual, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, -1, 30));

        txtInscricaoEstadual.setForeground(new java.awt.Color(0, 0, 0));
        txtInscricaoEstadual.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        painelDadosCadastrais.add(txtInscricaoEstadual, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 130, 30));

        lblDataSituacaoCadastral.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDataSituacaoCadastral.setForeground(new java.awt.Color(0, 0, 0));
        lblDataSituacaoCadastral.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDataSituacaoCadastral.setText("Data da Situação Cadastral");
        painelDadosCadastrais.add(lblDataSituacaoCadastral, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, -1, 30));

        lblCapitalSocial.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCapitalSocial.setForeground(new java.awt.Color(0, 0, 0));
        lblCapitalSocial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCapitalSocial.setText("Capital Social R$");
        painelDadosCadastrais.add(lblCapitalSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, -1, 30));

        lblNaturezaJuridica.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNaturezaJuridica.setForeground(new java.awt.Color(0, 0, 0));
        lblNaturezaJuridica.setText("Código e Descrição da Natureza Jurídica");
        painelDadosCadastrais.add(lblNaturezaJuridica, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, 30));

        txtNaturezaJuridica.setForeground(new java.awt.Color(0, 0, 0));
        painelDadosCadastrais.add(txtNaturezaJuridica, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 300, 30));

        txtDataAbertura.setForeground(new java.awt.Color(0, 0, 0));
        try {
            txtDataAbertura.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataAbertura.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        painelDadosCadastrais.add(txtDataAbertura, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, 90, 30));

        txtDataSituacaoCadastral.setForeground(new java.awt.Color(0, 0, 0));
        try {
            txtDataSituacaoCadastral.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataSituacaoCadastral.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        painelDadosCadastrais.add(txtDataSituacaoCadastral, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 60, 90, 30));

        txtCapitalSocial.setForeground(new java.awt.Color(0, 0, 0));
        painelDadosCadastrais.add(txtCapitalSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 170, 30));
        painelDadosCadastrais.add(lblStatusCnpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 30, 30));

        txtAtividadePrincipal.setColumns(20);
        txtAtividadePrincipal.setForeground(new java.awt.Color(0, 0, 0));
        txtAtividadePrincipal.setRows(5);
        txtAtividadePrincipal.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Código e Atividade Principal", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jScrollPane1.setViewportView(txtAtividadePrincipal);

        painelDadosCadastrais.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 730, -1));

        txtAtividadeSecundaria.setColumns(20);
        txtAtividadeSecundaria.setForeground(new java.awt.Color(0, 0, 0));
        txtAtividadeSecundaria.setRows(5);
        txtAtividadeSecundaria.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Código e Atividade Secundária", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jScrollPane2.setViewportView(txtAtividadeSecundaria);

        painelDadosCadastrais.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 730, -1));

        getContentPane().add(painelDadosCadastrais, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 760, 490));

        painelDadosEndereco.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Funções", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        painelDadosEndereco.setPreferredSize(new java.awt.Dimension(680, 120));
        painelDadosEndereco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBairro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblBairro.setForeground(new java.awt.Color(0, 0, 0));
        lblBairro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBairro.setText("Bairro");
        painelDadosEndereco.add(lblBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, -1, 30));

        txtBairro.setForeground(new java.awt.Color(0, 0, 0));
        painelDadosEndereco.add(txtBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 200, 30));

        lblCidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCidade.setForeground(new java.awt.Color(0, 0, 0));
        lblCidade.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCidade.setText("Cidade");
        painelDadosEndereco.add(lblCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 70, -1, 30));

        lblEstado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEstado.setForeground(new java.awt.Color(0, 0, 0));
        lblEstado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEstado.setText("Estado");
        painelDadosEndereco.add(lblEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 30, -1, 30));

        cmbEstado.setForeground(new java.awt.Color(0, 0, 0));
        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        cmbEstado.setMinimumSize(new java.awt.Dimension(80, 22));
        cmbEstado.setPreferredSize(new java.awt.Dimension(80, 22));
        painelDadosEndereco.add(cmbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 30, 90, 30));

        lblCep.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCep.setForeground(new java.awt.Color(0, 0, 0));
        lblCep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCep.setText("*CEP");
        painelDadosEndereco.add(lblCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 30));

        txtCidade.setForeground(new java.awt.Color(0, 0, 0));
        painelDadosEndereco.add(txtCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 70, 230, 30));

        lblEndereco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEndereco.setForeground(new java.awt.Color(0, 0, 0));
        lblEndereco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEndereco.setText("Endereço");
        painelDadosEndereco.add(lblEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, 30));

        txtEndereco.setForeground(new java.awt.Color(0, 0, 0));
        painelDadosEndereco.add(txtEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 290, 30));

        lblComplemento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblComplemento.setForeground(new java.awt.Color(0, 0, 0));
        lblComplemento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblComplemento.setText("Complemento");
        painelDadosEndereco.add(lblComplemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 30));

        txtComplemento.setForeground(new java.awt.Color(0, 0, 0));
        painelDadosEndereco.add(txtComplemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 390, 30));

        lblNumero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNumero.setForeground(new java.awt.Color(0, 0, 0));
        lblNumero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumero.setText("Nº");
        painelDadosEndereco.add(lblNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, -1, 30));

        txtNumero.setForeground(new java.awt.Color(0, 0, 0));
        txtNumero.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        painelDadosEndereco.add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, 70, 30));
        painelDadosEndereco.add(lblStatusCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 30, 30));

        lblTelefone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTelefone.setForeground(new java.awt.Color(0, 0, 0));
        lblTelefone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTelefone.setText("*Telefone");
        painelDadosEndereco.add(lblTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 30, -1, 30));

        txtTelefone.setForeground(new java.awt.Color(0, 0, 0));
        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        painelDadosEndereco.add(txtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 30, 130, 30));

        btnCep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search_icon.png"))); // NOI18N
        btnCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCepActionPerformed(evt);
            }
        });
        painelDadosEndereco.add(btnCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 30, 30));

        txtCep.setForeground(new java.awt.Color(0, 0, 0));
        painelDadosEndereco.add(txtCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 100, 30));

        getContentPane().add(painelDadosEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 1050, 120));

        painelFuncoes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Funções", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        painelFuncoes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add - large.png"))); // NOI18N
        btnAdicionar.setToolTipText("Adicionar cliente");
        btnAdicionar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        painelFuncoes.add(btnAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        btnDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete - large.png"))); // NOI18N
        btnDeletar.setToolTipText("Deletar cliente");
        btnDeletar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeletar.setEnabled(false);
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });
        painelFuncoes.add(btnDeletar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, -1));

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/edit - large.png"))); // NOI18N
        btnAlterar.setToolTipText("Alterar dados do cliente");
        btnAlterar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        painelFuncoes.add(btnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/limpar - large.png"))); // NOI18N
        btnLimpar.setToolTipText("Limpar formulário");
        btnLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpar.setEnabled(false);
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        painelFuncoes.add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search - large.png"))); // NOI18N
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        painelFuncoes.add(btnPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        getContentPane().add(painelFuncoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 60, 250, 310));

        painelDataCadastro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Funções", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        painelDataCadastro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDataCadastro.setEditable(false);
        txtDataCadastro.setForeground(new java.awt.Color(0, 0, 0));
        txtDataCadastro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        painelDataCadastro.add(txtDataCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 170, 30));

        getContentPane().add(painelDataCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 0, 190, 60));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Funções", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(250, 70));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtResponsalvel.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(txtResponsalvel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 170, 30));

        lblResponsavel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblResponsavel.setForeground(new java.awt.Color(0, 0, 0));
        lblResponsavel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResponsavel.setText("*Responsável");
        jPanel3.add(lblResponsavel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 30));

        lblCelular.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCelular.setForeground(new java.awt.Color(0, 0, 0));
        lblCelular.setText("Celular");
        jPanel3.add(lblCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, 30));

        txtCelular.setForeground(new java.awt.Color(0, 0, 0));
        try {
            txtCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel3.add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 170, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 390, 280, 100));

        lblCliCamposObrigatorios.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCliCamposObrigatorios.setForeground(new java.awt.Color(204, 0, 0));
        lblCliCamposObrigatorios.setText("*Campos Obrigatórios");
        getContentPane().add(lblCliCamposObrigatorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 370, -1, -1));

        setBounds(0, 0, 1080, 650);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        // Chamando o metodo adicionar
        try {
            EmpresaBS empresabs = new EmpresaBS();
            empresabs.adicionar();
        } catch (SQLException ex) {
        }
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        // Chamando o metodo deletar
        Empresa empresa = new Empresa();
        empresa.setTxtId(txtId.getText());
        empresa.empresadao.deletarEmpresa(empresa);
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // Chamando o metodo alterar
        try {
            EmpresaBS empresabs = new EmpresaBS();
            empresabs.alterar();
        } catch (SQLException ex) {
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // Chamando o metodo limpar formulário
        EmpresaBS empresabs = new EmpresaBS();
        empresabs.limparCampos();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // TODO add your handling code here:
        EmpresaBS empresabs = new EmpresaBS();
        empresabs.consultar();
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void txtCnpjKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCnpjKeyReleased
        // TODO add your handling code here:
        try {
            EmpresaBS empresabs = new EmpresaBS();
            empresabs.consultaCnpj();
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_txtCnpjKeyReleased

    private void btnCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCepActionPerformed
        // TODO add your handling code here:
       // EmpresaBS empresabs = new EmpresaBS();
       // empresabs.consultarcep();
    }//GEN-LAST:event_btnCepActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnAdicionar;
    public static javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCep;
    public static javax.swing.JButton btnDeletar;
    public static javax.swing.JButton btnLimpar;
    public static javax.swing.JButton btnPesquisar;
    public static javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCapitalSocial;
    public static javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblCep;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblCliCamposObrigatorios;
    private javax.swing.JLabel lblCnpj;
    private javax.swing.JLabel lblComplemento;
    private javax.swing.JLabel lblDataAbertura;
    private javax.swing.JLabel lblDataSituacaoCadastral;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblInscricaoEstadual;
    private javax.swing.JLabel lblNaturezaJuridica;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNomeFantasia;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblPorte;
    public static javax.swing.JLabel lblResponsavel;
    private javax.swing.JLabel lblSituacaoCadastral;
    public static javax.swing.JLabel lblStatusCep;
    public static javax.swing.JLabel lblStatusCnpj;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JPanel painelDadosCadastrais;
    private javax.swing.JPanel painelDadosEndereco;
    private javax.swing.JPanel painelDataCadastro;
    private javax.swing.JPanel painelFuncoes;
    private javax.swing.JPanel painelId;
    public static javax.swing.JTextArea txtAtividadePrincipal;
    public static javax.swing.JTextArea txtAtividadeSecundaria;
    public static javax.swing.JTextField txtBairro;
    public static javax.swing.JTextField txtCapitalSocial;
    public static javax.swing.JFormattedTextField txtCelular;
    public static javax.swing.JTextField txtCep;
    public static javax.swing.JTextField txtCidade;
    public static javax.swing.JTextField txtCnpj;
    public static javax.swing.JTextField txtComplemento;
    public static javax.swing.JFormattedTextField txtDataAbertura;
    public static javax.swing.JTextField txtDataCadastro;
    public static javax.swing.JFormattedTextField txtDataSituacaoCadastral;
    public static javax.swing.JTextField txtEmail;
    public static javax.swing.JTextField txtEndereco;
    public static javax.swing.JTextField txtId;
    public static javax.swing.JTextField txtInscricaoEstadual;
    public static javax.swing.JTextField txtNaturezaJuridica;
    public static javax.swing.JTextField txtNome;
    public static javax.swing.JTextField txtNomeFantasia;
    public static javax.swing.JTextField txtNumero;
    public static javax.swing.JTextField txtPorte;
    public static javax.swing.JTextField txtResponsalvel;
    public static javax.swing.JTextField txtSituacaoCadastral;
    public static javax.swing.JFormattedTextField txtTelefone;
    public static javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
