/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import Atxy2k.CustomTextField.RestrictedTextField;
import business.FuncionarioBS;

/**
 *
 * @author nilton.brito
 */
public class TelaCadastroFuncionario extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaCadastroUsuario
     */
    public TelaCadastroFuncionario() {
        initComponents();
        RestrictedTextField validarMatricula;
        validarMatricula = new RestrictedTextField(txtMatricula);
        validarMatricula.setOnlyNums(true);
        validarMatricula.setLimit(3);
        RestrictedTextField validarUsuario;
        validarUsuario = new RestrictedTextField(txtNome);
        validarUsuario.setLimit(50);
        RestrictedTextField validarFone;
        validarFone = new RestrictedTextField(txtCelular);
        validarFone.setLimit(20);
        RestrictedTextField validarLogin;
        validarLogin = new RestrictedTextField(txtLogin);
        validarLogin.setLimit(20);
        RestrictedTextField validarSenha;
        validarSenha = new RestrictedTextField(txtSenha);
        validarSenha.setLimit(250);
        RestrictedTextField validar = new RestrictedTextField(txtCep);
        validar.setOnlyNums(true);
        validar.setLimit(8);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPrincipal = new javax.swing.JPanel();
        lblInfo = new javax.swing.JLabel();
        painelPesquisar = new javax.swing.JPanel();
        txtPesquisar = new javax.swing.JTextField();
        lblPesquisar = new javax.swing.JLabel();
        painelFinanceiro = new javax.swing.JPanel();
        lblCargo = new javax.swing.JLabel();
        txtUsuCargo = new javax.swing.JTextField();
        lblSalario = new javax.swing.JLabel();
        txtUsuSalario = new javax.swing.JTextField();
        painelDadosEndereco = new javax.swing.JPanel();
        lblEndereco = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        lblBairro = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        lblCidade = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox<>();
        lblCep = new javax.swing.JLabel();
        txtCep = new javax.swing.JTextField();
        lblStatusCep = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        lblNumero = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        lblComplemento = new javax.swing.JLabel();
        txtComplemento = new javax.swing.JTextField();
        txtComplemento2 = new javax.swing.JTextField();
        lblComplemento2 = new javax.swing.JLabel();
        painelId = new javax.swing.JPanel();
        txtId = new javax.swing.JTextField();
        painelAcesso = new javax.swing.JPanel();
        lblLogin = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        lblSenha = new javax.swing.JLabel();
        lblPerfil = new javax.swing.JLabel();
        cmbPerfil = new javax.swing.JComboBox<>();
        painelStatus = new javax.swing.JPanel();
        cmbStatus = new javax.swing.JComboBox<>();
        chkSenha = new javax.swing.JCheckBox();
        txtSenha = new javax.swing.JPasswordField();
        painelMatricula = new javax.swing.JPanel();
        txtMatricula = new javax.swing.JTextField();
        painelDadosCadastrais = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblCpf = new javax.swing.JLabel();
        lblCelular = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtCpf = new javax.swing.JFormattedTextField();
        txtCelular = new javax.swing.JFormattedTextField();
        lblSobrenome = new javax.swing.JLabel();
        txtSobrenome = new javax.swing.JTextField();
        lblRg = new javax.swing.JLabel();
        txtRg = new javax.swing.JFormattedTextField();
        cmbSexo = new javax.swing.JComboBox<>();
        lblSexo = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JFormattedTextField();
        painelDataCadastro = new javax.swing.JPanel();
        lblDataCad = new javax.swing.JLabel();
        painelBotoes = new javax.swing.JPanel();
        btnAdicionar = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaUsuario = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastro de Funcionários");
        setPreferredSize(new java.awt.Dimension(1080, 650));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        painelPrincipal.setPreferredSize(new java.awt.Dimension(1070, 618));
        painelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInfo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblInfo.setForeground(new java.awt.Color(204, 0, 0));
        lblInfo.setText("*Campos Obrigatórios");
        painelPrincipal.add(lblInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 390, -1, -1));

        painelPesquisar.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisar"));
        painelPesquisar.setForeground(new java.awt.Color(0, 0, 0));
        painelPesquisar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPesquisar.setForeground(new java.awt.Color(0, 0, 0));
        txtPesquisar.setToolTipText("Pesquisa dinâmica do usuário");
        txtPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarKeyReleased(evt);
            }
        });
        painelPesquisar.add(txtPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 230, 30));

        lblPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search_icon.png"))); // NOI18N
        painelPesquisar.add(lblPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 30, -1));

        painelPrincipal.add(painelPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 300, 60));

        painelFinanceiro.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Financeiro"));
        painelFinanceiro.setForeground(new java.awt.Color(0, 0, 0));
        painelFinanceiro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCargo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCargo.setForeground(new java.awt.Color(0, 0, 0));
        lblCargo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCargo.setText("Cargo:");
        painelFinanceiro.add(lblCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 30));

        txtUsuCargo.setForeground(new java.awt.Color(0, 0, 0));
        painelFinanceiro.add(txtUsuCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 190, 30));

        lblSalario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSalario.setForeground(new java.awt.Color(0, 0, 0));
        lblSalario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSalario.setText("Salário: R$");
        painelFinanceiro.add(lblSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 30));

        txtUsuSalario.setForeground(new java.awt.Color(0, 0, 0));
        painelFinanceiro.add(txtUsuSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 190, 30));

        painelPrincipal.add(painelFinanceiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 230, 290, 110));

        painelDadosEndereco.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados de Endereço"));
        painelDadosEndereco.setForeground(new java.awt.Color(0, 0, 0));
        painelDadosEndereco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEndereco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEndereco.setForeground(new java.awt.Color(0, 0, 0));
        lblEndereco.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEndereco.setText("Endereço:");
        painelDadosEndereco.add(lblEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 60, 30));

        txtEndereco.setForeground(new java.awt.Color(0, 0, 0));
        painelDadosEndereco.add(txtEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 280, 30));

        lblBairro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblBairro.setForeground(new java.awt.Color(0, 0, 0));
        lblBairro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBairro.setText("Bairro:");
        painelDadosEndereco.add(lblBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 30));

        txtBairro.setForeground(new java.awt.Color(0, 0, 0));
        painelDadosEndereco.add(txtBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 200, 30));

        lblCidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCidade.setForeground(new java.awt.Color(0, 0, 0));
        lblCidade.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCidade.setText("Cidade:");
        painelDadosEndereco.add(lblCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, 30));

        lblEstado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEstado.setForeground(new java.awt.Color(0, 0, 0));
        lblEstado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEstado.setText("Estado:");
        painelDadosEndereco.add(lblEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, -1, 30));

        cmbEstado.setForeground(new java.awt.Color(0, 0, 0));
        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        painelDadosEndereco.add(cmbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, 90, 30));

        lblCep.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCep.setForeground(new java.awt.Color(0, 0, 0));
        lblCep.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCep.setText("*CEP:");
        painelDadosEndereco.add(lblCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 30));

        txtCep.setForeground(new java.awt.Color(0, 0, 0));
        txtCep.setMinimumSize(new java.awt.Dimension(60, 22));
        txtCep.setPreferredSize(new java.awt.Dimension(60, 22));
        txtCep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCepKeyReleased(evt);
            }
        });
        painelDadosEndereco.add(txtCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 150, 30));
        painelDadosEndereco.add(lblStatusCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 30, 30));

        txtCidade.setForeground(new java.awt.Color(0, 0, 0));
        painelDadosEndereco.add(txtCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 230, 30));

        lblNumero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNumero.setForeground(new java.awt.Color(0, 0, 0));
        lblNumero.setText("Nº");
        painelDadosEndereco.add(lblNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 30, -1, 30));

        txtNumero.setForeground(new java.awt.Color(0, 0, 0));
        painelDadosEndereco.add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, 60, 30));

        lblComplemento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblComplemento.setForeground(new java.awt.Color(0, 0, 0));
        lblComplemento.setText("Complemento:");
        painelDadosEndereco.add(lblComplemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 30));

        txtComplemento.setForeground(new java.awt.Color(0, 0, 0));
        painelDadosEndereco.add(txtComplemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 230, 30));

        txtComplemento2.setForeground(new java.awt.Color(0, 0, 0));
        painelDadosEndereco.add(txtComplemento2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 230, 30));

        lblComplemento2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblComplemento2.setForeground(new java.awt.Color(0, 0, 0));
        lblComplemento2.setText("Complemento:");
        painelDadosEndereco.add(lblComplemento2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, -1, 30));

        painelPrincipal.add(painelDadosEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 730, 160));

        painelId.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro ID"));
        painelId.setForeground(new java.awt.Color(0, 0, 0));
        painelId.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtId.setEditable(false);
        txtId.setForeground(new java.awt.Color(0, 0, 0));
        txtId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        painelId.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, 30));

        painelPrincipal.add(painelId, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 100, 60));

        painelAcesso.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados de Acesso"));
        painelAcesso.setForeground(new java.awt.Color(0, 0, 0));
        painelAcesso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(0, 0, 0));
        lblLogin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblLogin.setText("*Login:");
        painelAcesso.add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 30));

        txtLogin.setForeground(new java.awt.Color(0, 0, 0));
        painelAcesso.add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 200, 30));

        lblSenha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSenha.setForeground(new java.awt.Color(0, 0, 0));
        lblSenha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSenha.setText("*Senha:");
        painelAcesso.add(lblSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 30));

        lblPerfil.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPerfil.setForeground(new java.awt.Color(0, 0, 0));
        lblPerfil.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPerfil.setText("*Perfil:");
        painelAcesso.add(lblPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, 30));

        cmbPerfil.setForeground(new java.awt.Color(0, 0, 0));
        cmbPerfil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Administrador", "Gerente", "Usuario", "Restrito" }));
        painelAcesso.add(cmbPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 200, 30));

        painelStatus.setBorder(javax.swing.BorderFactory.createTitledBorder("*Status"));
        painelStatus.setForeground(new java.awt.Color(0, 0, 0));
        painelStatus.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbStatus.setForeground(new java.awt.Color(0, 0, 0));
        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Ativo", "Inativo" }));
        painelStatus.add(cmbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 18, 90, 30));

        painelAcesso.add(painelStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 130, 60));

        chkSenha.setText("Alterar a senha");
        chkSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSenhaActionPerformed(evt);
            }
        });
        painelAcesso.add(chkSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, -1, -1));

        txtSenha.setForeground(new java.awt.Color(0, 0, 0));
        painelAcesso.add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 200, 30));

        painelPrincipal.add(painelAcesso, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, 290, 220));

        painelMatricula.setBorder(javax.swing.BorderFactory.createTitledBorder("*Matricula"));
        painelMatricula.setForeground(new java.awt.Color(0, 0, 0));
        painelMatricula.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtMatricula.setForeground(new java.awt.Color(0, 0, 0));
        txtMatricula.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMatricula.setToolTipText("Informe a matricula");
        painelMatricula.add(txtMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, 30));

        painelPrincipal.add(painelMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 100, 60));

        painelDadosCadastrais.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Cadastrais"));
        painelDadosCadastrais.setForeground(new java.awt.Color(0, 0, 0));
        painelDadosCadastrais.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNome.setForeground(new java.awt.Color(0, 0, 0));
        lblNome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNome.setText("*Nome:");
        painelDadosCadastrais.add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 30));

        lblEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(0, 0, 0));
        lblEmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEmail.setText("*E-mail:");
        painelDadosCadastrais.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, -1, 30));

        lblCpf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCpf.setForeground(new java.awt.Color(0, 0, 0));
        lblCpf.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCpf.setText("*CPF:");
        painelDadosCadastrais.add(lblCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 30));

        lblCelular.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCelular.setForeground(new java.awt.Color(0, 0, 0));
        lblCelular.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCelular.setText("*Celular:");
        painelDadosCadastrais.add(lblCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, -1, 30));

        txtNome.setForeground(new java.awt.Color(0, 0, 0));
        painelDadosCadastrais.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 200, 30));

        txtEmail.setForeground(new java.awt.Color(0, 0, 0));
        painelDadosCadastrais.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 250, 30));

        txtCpf.setForeground(new java.awt.Color(0, 0, 0));
        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        painelDadosCadastrais.add(txtCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 150, 30));

        txtCelular.setForeground(new java.awt.Color(0, 0, 0));
        try {
            txtCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        painelDadosCadastrais.add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 150, 30));

        lblSobrenome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSobrenome.setForeground(new java.awt.Color(0, 0, 0));
        lblSobrenome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSobrenome.setText("Sobrenome:");
        painelDadosCadastrais.add(lblSobrenome, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, 30));

        txtSobrenome.setForeground(new java.awt.Color(0, 0, 0));
        painelDadosCadastrais.add(txtSobrenome, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 350, 30));

        lblRg.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRg.setForeground(new java.awt.Color(0, 0, 0));
        lblRg.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRg.setText("RG:");
        painelDadosCadastrais.add(lblRg, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, 30));

        txtRg.setForeground(new java.awt.Color(0, 0, 0));
        try {
            txtRg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        painelDadosCadastrais.add(txtRg, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 150, 30));

        cmbSexo.setForeground(new java.awt.Color(0, 0, 0));
        cmbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Masculino", "Feminino", "Indefinido" }));
        painelDadosCadastrais.add(cmbSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, 90, 30));

        lblSexo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSexo.setForeground(new java.awt.Color(0, 0, 0));
        lblSexo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSexo.setText("Sexo:");
        painelDadosCadastrais.add(lblSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, -1, 30));

        lblTelefone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTelefone.setForeground(new java.awt.Color(0, 0, 0));
        lblTelefone.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTelefone.setText("Telefone:");
        painelDadosCadastrais.add(lblTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, -1, 30));

        txtTelefone.setForeground(new java.awt.Color(0, 0, 0));
        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        painelDadosCadastrais.add(txtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 150, 30));

        painelPrincipal.add(painelDadosCadastrais, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 730, 160));

        painelDataCadastro.setBorder(javax.swing.BorderFactory.createTitledBorder("Data do Cadastro:"));
        painelDataCadastro.setForeground(new java.awt.Color(0, 0, 0));
        painelDataCadastro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDataCad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDataCad.setForeground(new java.awt.Color(0, 0, 0));
        lblDataCad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        painelDataCadastro.add(lblDataCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 180, 30));

        painelPrincipal.add(painelDataCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 200, 60));

        painelBotoes.setBorder(javax.swing.BorderFactory.createTitledBorder("Funções"));
        painelBotoes.setForeground(new java.awt.Color(0, 0, 0));
        painelBotoes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add.png"))); // NOI18N
        btnAdicionar.setToolTipText("Adicionar usuário");
        btnAdicionar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        painelBotoes.add(btnAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        btnDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete.png"))); // NOI18N
        btnDeletar.setToolTipText("Deletar usuário");
        btnDeletar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeletar.setEnabled(false);
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });
        painelBotoes.add(btnDeletar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/edit.png"))); // NOI18N
        btnEditar.setToolTipText("Alterar dados do usuário");
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditar.setEnabled(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        painelBotoes.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/limpar.png"))); // NOI18N
        btnLimpar.setToolTipText("Limpar formulário");
        btnLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpar.setEnabled(false);
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        painelBotoes.add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        painelPrincipal.add(painelBotoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 340, 290, 70));

        tabelaUsuario = new javax.swing.JTable(){
            public boolean isCellEditable(int eowIndex, int colIndex){
                return false;
            }
        };
        tabelaUsuario.setForeground(new java.awt.Color(0, 0, 0));
        tabelaUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Matricula", "Nome", "Sobrenome", "CPF", "RG", "Celular", "E-mail", "Sexo", "Endereço", "Bairro", "Cidade", "Estado", "CEP", "Login", "Senha", "Perfil", "Status", "Cargo", "Salario", "Data de Cadastro", "Data de Atualaização"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaUsuario.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabelaUsuario.setFocusable(false);
        tabelaUsuario.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabelaUsuario.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabelaUsuario.getTableHeader().setReorderingAllowed(false);
        tabelaUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaUsuarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaUsuario);

        painelPrincipal.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 1040, 190));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 1062, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
        );

        setBounds(0, 0, 1080, 650);
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened

        chkSenha.setSelected(false);
        chkSenha.setVisible(false);
    }//GEN-LAST:event_formInternalFrameOpened

    private void tabelaUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaUsuarioMouseClicked
        // chamando o metodo para setar os campo
        FuncionarioBS funcionarioBS = new FuncionarioBS();
        funcionarioBS.setarCampos();
    }//GEN-LAST:event_tabelaUsuarioMouseClicked

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        // Chamando o metodo adicionar
        FuncionarioBS funcionarioBS = new FuncionarioBS();
        funcionarioBS.adicionarFuncionario();
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        // Chamando o metodo deletar
        FuncionarioBS funcionarioBS = new FuncionarioBS();
        funcionarioBS.deletarFuncionario();
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // Chamando o metodo alterar 
        FuncionarioBS funcionarioBS = new FuncionarioBS();
        funcionarioBS.editarFuncionario();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // Chamando o metodo limpar formulário
        FuncionarioBS funcionarioBS = new FuncionarioBS();
        funcionarioBS.limparCampos();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void chkSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSenhaActionPerformed
        txtSenha.setText(null);
        txtSenha.requestFocus();
        txtSenha.setEnabled(true);
        chkSenha.setEnabled(false);
    }//GEN-LAST:event_chkSenhaActionPerformed

    private void txtCepKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCepKeyReleased
        // TODO add your handling code here:
        FuncionarioBS funcionarioBS = new FuncionarioBS();
        funcionarioBS.consultaCep();
    }//GEN-LAST:event_txtCepKeyReleased

    private void txtPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarKeyReleased
        // Chamando o metodo pesquisar clientes
        FuncionarioBS funcionarioBS = new FuncionarioBS();
        funcionarioBS.pesquisarFuncionario();
    }//GEN-LAST:event_txtPesquisarKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnAdicionar;
    public static javax.swing.JButton btnDeletar;
    public static javax.swing.JButton btnEditar;
    public static javax.swing.JButton btnLimpar;
    public static javax.swing.JCheckBox chkSenha;
    public static javax.swing.JComboBox<String> cmbEstado;
    public static javax.swing.JComboBox<String> cmbPerfil;
    public static javax.swing.JComboBox<String> cmbSexo;
    public static javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblCep;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblComplemento;
    private javax.swing.JLabel lblComplemento2;
    private javax.swing.JLabel lblCpf;
    public static javax.swing.JLabel lblDataCad;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblPerfil;
    public static javax.swing.JLabel lblPesquisar;
    private javax.swing.JLabel lblRg;
    private javax.swing.JLabel lblSalario;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblSobrenome;
    public static javax.swing.JLabel lblStatusCep;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JPanel painelAcesso;
    private javax.swing.JPanel painelBotoes;
    private javax.swing.JPanel painelDadosCadastrais;
    private javax.swing.JPanel painelDadosEndereco;
    private javax.swing.JPanel painelDataCadastro;
    private javax.swing.JPanel painelFinanceiro;
    private javax.swing.JPanel painelId;
    private javax.swing.JPanel painelMatricula;
    private javax.swing.JPanel painelPesquisar;
    private javax.swing.JPanel painelPrincipal;
    private javax.swing.JPanel painelStatus;
    public static javax.swing.JTable tabelaUsuario;
    public static javax.swing.JTextField txtBairro;
    public static javax.swing.JFormattedTextField txtCelular;
    public static javax.swing.JTextField txtCep;
    public static javax.swing.JTextField txtCidade;
    public static javax.swing.JTextField txtComplemento;
    public static javax.swing.JTextField txtComplemento2;
    public static javax.swing.JFormattedTextField txtCpf;
    public static javax.swing.JTextField txtEmail;
    public static javax.swing.JTextField txtEndereco;
    public static javax.swing.JTextField txtId;
    public static javax.swing.JTextField txtLogin;
    public static javax.swing.JTextField txtMatricula;
    public static javax.swing.JTextField txtNome;
    public static javax.swing.JTextField txtNumero;
    public static javax.swing.JTextField txtPesquisar;
    public static javax.swing.JFormattedTextField txtRg;
    public static javax.swing.JPasswordField txtSenha;
    public static javax.swing.JTextField txtSobrenome;
    public static javax.swing.JFormattedTextField txtTelefone;
    public static javax.swing.JTextField txtUsuCargo;
    public static javax.swing.JTextField txtUsuSalario;
    // End of variables declaration//GEN-END:variables
}
